Repository SarahE-Dev/bloom-housing, pull requests merged in 2025-05, with the labels that each got.

#53 feat(confirmation & terms): resources displayed based on model result
  shared-helpers/src/locales/general.json
  sites/public/src/pages/applications/review/confirmation.tsx
  sites/public/src/pages/applications/review/terms.tsx
Labels: enhancement

#65 Add Risk Assessment PDF for PII Access Location to Project Tracking
  project-tracking/risk-assessment.pdf
Labels: documentation

#68 feat: update form submission to match model
  api/src/services/application.service.ts
  api/src/utilities/model.helper.ts
Labels: bug, enhancement

#71 initial semantic search implementation
  model/docker-compose.yaml
  model/semantic_search/Dockerfile
  model/semantic_search/embeddings.npy
  model/semantic_search/main.py
  model/semantic_search/prepare_data.py
  model/semantic_search/providers.json
  model/semantic_search/requirements.txt
  sites/public/src/components/applications/CustomResults.jsx
  sites/public/src/pages/applications/review/confirmation.tsx
Labels: must have
